version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=doc_bd
      - POSTGRES_USER=rennan
      - POSTGRES_PASSWORD=semsenha132
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn documentos.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./documentos:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=prod-django-insecure-a!b@c#d$e%f^g&h*i(j)k_l-m+n=o
      - DEBUG=0
      - ALLOWED_HOSTS=45.140.193.93,localhost,127.0.0.1
      - DB_HOST=db
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
