# Generated by Django 5.2.1 on 2025-05-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_docs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(
                blank=True, null=True, upload_to="upload_documentos/"
            ),
        ),
    ]
