# Generated by Django 5.2.1 on 2025-05-27 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_docs", "0003_documento_atualizado_por_documento_criado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documento",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funcionario",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
