# Generated by Django 5.2.1 on 2025-05-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_docs", "0005_registrolog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RegistroLog",
        ),
    ]
