# Generated by Django 5.2.3 on 2025-06-13 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_docs', '0008_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestorlocal',
            name='local_mobilizacao',
        ),
        migrations.AddField(
            model_name='gestorlocal',
            name='locais',
            field=models.ManyToManyField(related_name='gestores', to='gestao_docs.localmobilizacao'),
        ),
        migrations.AlterField(
            model_name='gestorlocal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
