"""
Django settings for documentos project.

Generated by 'django-admin startproject' using Django 5.2.1.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key

# —————————————————————————————————————————————————————————————————————————
# BASE DIR
# —————————————————————————————————————————————————————————————————————————
BASE_DIR = Path(__file__).resolve().parent.parent


# —————————————————————————————————————————————————————————————————————————
# SECURITY
# —————————————————————————————————————————————————————————————————————————
SECRET_KEY = os.environ.get('SECRET_KEY', get_random_secret_key())
DEBUG = os.environ.get('DEBUG', '0') == '1'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# —————————————————————————————————————————————————————————————————————————
# APPS
# —————————————————————————————————————————————————————————————————————————
INSTALLED_APPS = [
    # contrib
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # suas apps
    'gestao_docs',
    # terceiros
    'widget_tweaks',
    'chartjs',
    'crispy_forms',
    'django_filters',
    'rest_framework',
    'rest_framework.authtoken',
]


# —————————————————————————————————————————————————————————————————————————
# MIDDLEWARE
# —————————————————————————————————————————————————————————————————————————
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",      # serve estáticos em produção
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]


# —————————————————————————————————————————————————————————————————————————
# URLS & WSGI
# —————————————————————————————————————————————————————————————————————————
ROOT_URLCONF = "documentos.urls"
WSGI_APPLICATION = "documentos.wsgi.application"


# —————————————————————————————————————————————————————————————————————————
# TEMPLATES
# —————————————————————————————————————————————————————————————————————————
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # se tiver templates globais, adicione aqui
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# —————————————————————————————————————————————————————————————————————————
# DATABASE
# —————————————————————————————————————————————————————————————————————————
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get('DB_NAME', 'doc_bd'),
        "USER": os.environ.get('DB_USER', 'postgres'),
        "PASSWORD": os.environ.get('DB_PASSWORD', ''),
        "HOST": os.environ.get('DB_HOST', 'localhost'),
        "PORT": os.environ.get('DB_PORT', '5432'),
    }
}


# —————————————————————————————————————————————————————————————————————————
# AUTH & REDIRECTS
# —————————————————————————————————————————————————————————————————————————
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'


# —————————————————————————————————————————————————————————————————————————
# MEDIA (uploads)
# —————————————————————————————————————————————————————————————————————————
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# —————————————————————————————————————————————————————————————————————————
# STATIC FILES
# —————————————————————————————————————————————————————————————————————————
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'    # destino do collectstatic
STATICFILES_DIRS = [
    BASE_DIR / 'gestao_docs' / 'static',   # única origem dos seus css/js/img
]
# compressão e cache busting em produção
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# —————————————————————————————————————————————————————————————————————————
# INTERNATIONALIZATION
# —————————————————————————————————————————————————————————————————————————
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# —————————————————————————————————————————————————————————————————————————
# AUTO FIELD
# —————————————————————————————————————————————————————————————————————————
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# —————————————————————————————————————————————————————————————————————————
# CRISPY FORMS
# —————————————————————————————————————————————————————————————————————————
CRISPY_TEMPLATE_PACK = 'bootstrap4'


# —————————————————————————————————————————————————————————————————————————
# REST FRAMEWORK
# —————————————————————————————————————————————————————————————————————————
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}


# —————————————————————————————————————————————————————————————————————————
# EMAIL (preencha para notificações)
# —————————————————————————————————————————————————————————————————————————
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''  # seu e-mail
EMAIL_HOST_PASSWORD = ''  # sua senha


# —————————————————————————————————————————————————————————————————————————
# CACHE
# —————————————————————————————————————————————————————————————————————————
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}
